CREATE DATABASE INICIO01;
USE INICIO01;
CREATE TABLE PERSONAS(ID INTEGER PRIMARY KEY AUTO_INCREMENT, NOMBRES VARCHAR(255), APELLIDOS VARCHAR(255), PROGRAMA VARCHAR(255));
INSERT INTO PERSONAS (NOMBRES, APELLIDOS, PROGRAMA )VALUES ("JESUS", "PINILLA", "ING DE SOFTWARE");
INSERT INTO PERSONAS (NOMBRES, APELLIDOS, PROGRAMA )VALUES ("NICOLAS", "PINILLA", "ING DE SISTEMAS");
INSERT INTO PERSONAS (NOMBRES, APELLIDOS, PROGRAMA )VALUES ("MERY", "RODRIGUEZ", "ENFERMERIA");
SELECT * FROM PERSONAS